"""Static seed data for `ost_history`, generated from list.md by
`scripts/generate_history_seed.py`. Covers past rankings (batches 1-4);
the current ranking is backfilled directly from the live `osts` table
instead (see ost_tracker/db/migrations.py).
"""

SEED_ENTRIES: list[dict] = [
    {"title": 'Hollow Skies', "source": 'Final Fantasy VII', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@playboimadara'},
    {"title": 'Seven Rings in Hand', "source": 'Sonic and the Secret Rings', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Main Theme', "source": 'The Last of Us', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@playboimadara'},
    {"title": 'The Ala Mente', "source": "Ocean's Twelve", "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@yotsubaaan'},
    {"title": 'Midsummer Knights Dream', "source": 'Persona 3 (FES)', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@yotsubaaan'},
    {"title": 'Bridge Battle', "source": 'Sly Cooper: Thieves in Time', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Money Prologue Heist', "source": 'Grand Theft Auto V', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@vanjosu'},
    {"title": 'Back To Zero', "source": 'Fate/Zero', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'The Dovahkiin', "source": 'Skyrim', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@animewoob.sama'},
    {"title": 'Main Theme', "source": 'Metal Gear Solid 3: Snake Eater', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@animewoob.sama'},
    {"title": 'The Only Thing I Know For Real', "source": 'Metal Gear Rising: Revengeance', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@animewoob.sama'},
    {"title": 'Sonata in Darkness', "source": 'The Batman', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@4rias'},
    {"title": 'Luminous Sword', "source": 'Sword Art Online', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@vanjosu'},
    {"title": 'Xiao Theme', "source": 'Genshin Impact', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Like a Dream Come True', "source": 'Persona 4 Golden', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@mctarble'},
    {"title": 'Magus Theme', "source": 'Chrono Trigger', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Built To Kill', "source": 'Horizon Forbidden West', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": "Kaine's Salvation", "source": 'NieR Replicant', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@yotsubaaan'},
    {"title": 'Main Theme', "source": 'God of War (2018)', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@4rias'},
    {"title": "La Vie D'une Femme", "source": 'Blood Blockade Battlefront', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Cometh The Hour', "source": 'Bleach', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Agni Kai', "source": 'Avatar: The Last Airbender', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": "Sanji's Theme", "source": 'One Piece', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@vanjosu'},
    {"title": 'Abandoned Temple', "source": 'Tekken 7', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Hunt or be Hunted', "source": 'The Witcher 3: Wild Hunt', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Memories Of You', "source": 'Persona 3', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Ashes of Dreams', "source": 'NieR Replicant', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@yotsubaaan'},
    {"title": 'American Venom', "source": 'Red Dead Redemption II', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@vanjosu'},
    {"title": 'Connor Chase', "source": 'Detroit: Become Human', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Aruarian Dance', "source": 'Samurai Champloo', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@4rias'},
    {"title": 'Gogeta SSJ4 Dokkan Theme', "source": 'Dragon Ball Z: Dokkan Battle', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@animewoob.sama'},
    {"title": 'Black Suited', "source": 'Spider-Man 3', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@4rias'},
    {"title": 'World Championship Battle', "source": 'Pokémon (Gen 8)', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Champions Theme', "source": 'Pokémon (Gen 4)', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@vanjosu'},
    {"title": 'Divine Bloodlines', "source": 'Castlevania', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@animewoob.sama'},
    {"title": "Saitama's Theme", "source": 'One-Punch Man', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@playboimadara'},
    {"title": 'Fly Me To The Moon', "source": 'Neon Genesis Evangelion', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Running In The 90s', "source": 'Initial D', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Live And Learn', "source": 'Sonic Adventure 2', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Boss Theme', "source": 'Kid Icarus: Uprising', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Duel Climax 04', "source": 'Yu-Gi-Oh!', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@yotsubaaan'},
    {"title": 'It has to be this way', "source": 'Metal Gear Rising: Revengeance', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Slave Knight Gael', "source": 'Dark Souls III', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Birth Of A God', "source": 'Dragon Ball Super', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Main Theme', "source": 'Final Fantasy VII', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": "Light's Theme", "source": 'Death Note', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Main Theme', "source": 'Dark Souls III', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@playboimadara'},
    {"title": "Near's Theme", "source": 'Death Note', "batch_label": 'Batch 1: 2022 Original Ranking (Host: @tanjirosmizu)', "sender": '@playboimadara'},
    {"title": 'Tsurugi no Mai', "source": 'Samurai Champloo', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Made Warete Nee Jeneeka Shabo', "source": 'Gintama', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@fwxerx'},
    {"title": 'One Winged Angel', "source": 'Final Fantasy VII', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Forward', "source": 'Blue Giant', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'One Day', "source": 'Pirates of the Caribbean', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@kevnvrvs'},
    {"title": 'Fight!', "source": 'Slam Dunk', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Katawaredoki', "source": 'Your Name', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@uzidle'},
    {"title": 'Endwalker Trailer Theme', "source": 'Final Fantasy XIV', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@ulasius217'},
    {"title": 'Call your Name', "source": 'Attack on Titan', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@uzidle'},
    {"title": 'Mountain Pass', "source": "Baldur's Gate 3", "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Senna', "source": 'Bleach', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Ashes on the fire', "source": 'Attack on Titan', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@ulasius217'},
    {"title": 'Wiping all out', "source": 'Persona 3 Portable', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@uzidle'},
    {"title": 'Menu Theme', "source": 'Sonic Riders: Zero Gravity', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'On Our Way', "source": 'Final Fantasy VII', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@ulasius217'},
    {"title": 'Fantasy Note', "source": 'Honkai Impact 3rd', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Low of Solipsism', "source": 'Death Note', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Theme of Laura', "source": 'Silent Hill 2', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Vasto Lorde', "source": 'Bleach', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@kevnvrvs'},
    {"title": 'Main Theme', "source": 'DOOM Eternal', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Master of Shadows', "source": 'Persona 3 Portable', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Relaxing Medley', "source": 'Vinland Saga', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@kevnvrvs'},
    {"title": "Anakin's Evil Deeds", "source": 'Star Wars Episode III', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@kevnvrvs'},
    {"title": 'Killing my Love', "source": 'Initial D', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Kira Investigation Unit', "source": 'Death Note', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@ulasius217'},
    {"title": "Wally's Theme", "source": 'Pokémon Omega Ruby', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Quilge Opie vs Ichigo theme', "source": 'Bleach', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@kevnvrvs'},
    {"title": 'Kairi I', "source": 'Kingdom Hearts', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@ulasius217'},
    {"title": "Zelda's Lullaby", "source": 'The Legend of Zelda: OoT', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Last Surprise', "source": 'Persona 5', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Death by Glamour', "source": 'Undertale', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Kuroi Uta', "source": 'Drakengard', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Redeem The Future', "source": 'Xenoblade Chronicles 3', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Edge of Existence', "source": 'Kingdom Hearts', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Reverie', "source": 'Persona 4 Golden', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": "World's End Valentine", "source": 'OMORI', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Shadowblood Queen', "source": 'Final Fantasy VII Remake', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Way of Life', "source": 'Persona 3 Portable', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Find the Flame', "source": 'Final Fantasy XVI', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@uzidle'},
    {"title": 'A Beautiful Song', "source": 'NieR: Automata', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Number One', "source": 'Bleach', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@fwxerx'},
    {"title": 'Battle Theme', "source": 'Final Fantasy XVI', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Thanathos', "source": 'Neon Genesis Evangelion', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Heartbreak, Heartbreak!', "source": 'Persona 4 Golden', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@uzidle'},
    {"title": 'One Rainy Day', "source": 'The Melancholy of Haruhi', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Bauklötze', "source": 'Attack on Titan', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@fwxerx'},
    {"title": 'Vogel im Käfig', "source": 'Attack on Titan', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@fwxerx'},
    {"title": 'The Final Battle', "source": 'Elden Ring', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Color Your Night', "source": 'Persona 3 Reload', "batch_label": 'Batch 2: 2024 Group Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Been good to know ya', "source": 'Cyberpunk: Edgerunners', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@phrygianturk'},
    {"title": 'Towards the climax', "source": 'Death Note', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@phrygianturk'},
    {"title": 'What im Made Of', "source": 'Sonic Heroes', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Main Theme', "source": 'The Dark Knight', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@deluctant'},
    {"title": 'Möbius', "source": 'Gundam: Iron-Blooded Orphans', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@uzidle'},
    {"title": "Aerith's Theme", "source": 'Final Fantasy VII', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@phrygianturk'},
    {"title": 'Warriors of Valour', "source": 'Metaphor: ReFantazio', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'The Hammer of Thor', "source": 'God of War Ragnarök', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@srzk.1'},
    {"title": 'Invasion', "source": 'Bleach', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Destroyer of Worlds', "source": 'Oppenheimer', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@deluctant'},
    {"title": 'Bready Steady Go', "source": 'OMORI', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@uzidle'},
    {"title": 'L Destructor', "source": 'Beyblade Burst', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Ghost of Yarikawa', "source": 'Ghost of Tsushima', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Luffy the Trusted Man', "source": 'One Piece', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Passacaille in Barcelona', "source": 'Yuri!!! on Ice', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Senya', "source": 'Naruto', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Cornfield Chase', "source": 'Interstellar', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@deluctant'},
    {"title": 'Quietly Hidden In The Mountains', "source": 'Black Myth: Wukong', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Greater Together', "source": "Marvel's Spider-Man", "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@srzk.1'},
    {"title": 'Paraiso', "source": 'Michiko & Hatchin', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Soul of Cinder', "source": 'Dark Souls III', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Nibelheim', "source": 'Final Fantasy VII Remake', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@phrygianturk'},
    {"title": 'Stardust Speedway', "source": 'Sonic CD', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Main Theme', "source": 'Fire Emblem: Three Houses', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@uzidle'},
    {"title": 'Portals', "source": 'Avengers: Endgame', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@srzk.1'},
    {"title": 'Menu Theme', "source": 'Kingdom Hearts', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@phrygianturk'},
    {"title": 'Requiem of Silence', "source": 'Re:Zero', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Hopes and Dreams', "source": 'Undertale', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@uzidle'},
    {"title": 'Nothing is Won, Nothing is Lost', "source": 'Bleach', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Main Theme', "source": 'Goblin Slayer', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'All Star Rest Area', "source": 'Super Smash Bros. Brawl', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Burning Phase Special', "source": 'Inazuma Eleven', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Walpurgis No Kaiten', "source": 'Puella Magi Madoka Magica', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Footsteps of Doom', "source": 'Attack on Titan', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@deluctant'},
    {"title": 'Blades of Chaos', "source": 'God of War (2018)', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@srzk.1'},
    {"title": 'Full Moon Full Life', "source": 'Persona 3 Reload', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Song of Storms', "source": 'The Legend of Zelda: OoT', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@uzidle'},
    {"title": 'Licht und Schatten', "source": 'Tokyo Ghoul', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Lullaby of Resembool', "source": 'Fullmetal Alchemist: Brotherhood', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Actions in the Lower World', "source": 'Melty Blood', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'The Battle is To The Strong', "source": 'Fate/Zero', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Midgarsormr Phase 2', "source": 'Final Fantasy VII Remake', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Battle B2', "source": 'Shin Megami Tensei IV', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Infinity Castle', "source": 'Demon Slayer', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Elite Four', "source": 'Pokémon Alpha Sapphire', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@srzk.1'},
    {"title": 'Lost in Thoughts All Alone', "source": 'Fire Emblem Fates', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Friday Night', "source": 'Yakuza 0', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Artorias of The Abyss', "source": 'Dark Souls', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@deluctant'},
    {"title": 'In Times of War', "source": 'The Eminence in Shadow', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Gate of Steiner', "source": 'Steins;Gate', "batch_label": 'Batch 3: 2024 Annual Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Subhuman', "source": 'Devil May Cry 5', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@birb.josias'},
    {"title": 'Simple and Clean', "source": 'Kingdom Hearts', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Ken Theme', "source": 'Street Fighter II', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Hugo Vlad Theme', "source": 'Zenless Zone Zero', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@birb.josias'},
    {"title": 'To Zanarkand', "source": 'Final Fantasy X', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Moment of Impact', "source": 'Tekken 7', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Continued Story', "source": 'Code Geass R2', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Overtime', "source": 'Clash Royale', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@suvanjo'},
    {"title": 'Chaos Island Act 1', "source": 'Sonic Shadow Generations', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Path (A New Beginning)', "source": 'The Last of Us', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@suvanjo'},
    {"title": 'U No Hane', "source": 'The Girl Who Leapt Through Time', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Acoustic Image', "source": 'Touhou Project', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Tokyo', "source": 'Shin Megami Tensei IV', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Malkuth Battle 2', "source": 'Library of Ruina', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'The Sending', "source": 'Final Fantasy X', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@suvanjo'},
    {"title": 'Fragrance of Dark Coffee', "source": 'Ace Attorney', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Clocktower', "source": 'Castlevania', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Kasey', "source": 'Super Crooks', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@mr.tarble'},
    {"title": 'Battle Theme', "source": 'Final Fantasy VI', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Battle Against a True Hero', "source": 'Undertale', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@suvanjo'},
    {"title": "Black Zetsu's Theme", "source": 'Naruto Shippuden', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@kevnsitooo'},
    {"title": 'Kingdom of Predators', "source": 'Hunter x Hunter', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@fwxerx'},
    {"title": 'Nights of Night', "source": 'Touhou Project', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Gustave', "source": 'Clair Obscur: Expedition 33', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'I Beg You', "source": "Fate/stay night: Heaven's Feel", "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'The Birth of Merged Zamasu', "source": 'Dragon Ball Super', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@fwxerx'},
    {"title": 'Main Theme', "source": 'Street Fighter IV', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Gogeta Active Skill Theme', "source": 'Dragon Ball Z: Dokkan Battle', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@birb.josias'},
    {"title": 'The Way of the Ghost', "source": 'Ghost of Tsushima', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@fwxerx'},
    {"title": 'Corrupted Monk', "source": 'Sekiro: Shadows Die Twice', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Might + U', "source": 'My Hero Academia', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@fwxerx'},
    {"title": "Loki's Theme", "source": "Marvel Studios' Loki", "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@kevnsitooo'},
    {"title": 'Spring Blossom Diva', "source": 'Monster Hunter Wilds', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": "Ulquiorra's Theme", "source": 'Bleach: Brave Souls', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@kevnsitooo'},
    {"title": 'Father Gascoigne', "source": 'Bloodborne', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@fwxerx'},
    {"title": 'Alien Manifestation', "source": 'NieR: Automata', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": "N's Farewell", "source": 'Pokémon Omega Ruby', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@onon0ki'},
    {"title": 'Portrait Imparfait', "source": 'Clair Obscur: Expedition 33', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Etoile e Toi', "source": 'Kizumonogatari', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": "SWR Tenshi's theme", "source": 'Touhou Project', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@birb.josias'},
    {"title": 'Messmer, The Impaler', "source": 'Elden Ring', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@birb.josias'},
    {"title": "Sirène - Poème D'amour", "source": 'Clair Obscur: Expedition 33', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@suvanjo'},
    {"title": 'Moon Halo', "source": 'Honkai Impact 3rd', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@ginnfx'},
    {"title": 'Statue of God', "source": 'Solo Leveling', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@kevnsitooo'},
    {"title": 'Voices of the Chord', "source": '86 - Eighty Six', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Why', "source": 'Crisis Core: Final Fantasy VII', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@tanjirosmizu'},
    {"title": 'Bad Bully', "source": 'Kizumonogatari', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@kevnsitooo'},
    {"title": 'Main Theme', "source": 'Code Vein', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
    {"title": 'Déchire la Toile', "source": 'Clair Obscur: Expedition 33', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@cheese.in.toast'},
    {"title": 'Alive', "source": 'Shin Megami Tensei: Digital Devil Saga 2', "batch_label": 'Batch 4: 2025 Group Ranking (Host: @tanjirosmizu)', "sender": '@aman_zdn'},
]
